spring:
  profiles:
    active: test

---

spring:
  config:
      activate:
          on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/parkingDb
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 60000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  server:
    port: 8082
    error:
      include-message: always
      include-stacktrace: never

---

spring:
  config:
      activate:
          on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    generate-unique-name: false
    hikari:
      maximum-pool-size: 5
      connection-timeout: 60000
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
  server:
    port: 8083
    error:
      include-message: always
      include-stacktrace: never