drop table if exists car cascade;
drop table if exists car_driver cascade;
drop table if exists driver cascade;
drop table if exists parking_garage cascade;
drop table if exists parking_slot cascade;

create table car (id bigint generated by default as identity
                 , parking_slot_id bigint unique
                 , parking_started timestamp(6)
                 , brand varchar(255)
                 , license_plate varchar(255)
                 , model varchar(255)
                 , primary key (id));
create table car_driver (car_id bigint not null
                        , driver_id bigint not null
                        , primary key (car_id, driver_id));
create table driver (birthday date
                    , id bigint generated by default as identity
                    , driver_license varchar(255)
                    , first_name varchar(255)
                    , last_name varchar(255)
                    , phone_number varchar(255)
                    , primary key (id));
create table parking_garage (capacity integer
                            , construction_date date
                            , parking_rate integer
                            , id bigint generated by default as identity
                            , building varchar(255)
                            , city varchar(255)
                            , country varchar(255)
                            , name varchar(255)
                            , state varchar(255)
                            , street varchar(255)
                            , primary key (id));
create table parking_slot (occupied boolean not null
                          , slot_number integer
                          , id bigint generated by default as identity
                          , parking_garage_id bigint
                          , primary key (id));