drop table if exists car cascade;
drop table if exists car_driver cascade;
drop table if exists driver cascade;
drop table if exists parking_garage cascade;
drop table if exists parking_slot cascade;

create table car (id bigint generated by default as identity
                 , parking_slot_id bigint unique
                 , parking_started timestamp(6)
                 , brand varchar(255)
                 , license_plate varchar(255)
                 , model varchar(255)
                 , primary key (id));
create table parking_garage (capacity integer
                            , construction_date date
                            , parking_rate integer
                            , id bigint generated by default as identity
                            , building varchar(255)
                            , city varchar(255)
                            , country varchar(255)
                            , name varchar(255)
                            , state varchar(255)
                            , street varchar(255)
                            , primary key (id));
create table parking_slot (occupied boolean not null
                          , slot_number integer
                          , id bigint generated by default as identity
                          , parking_garage_id bigint
                          , primary key (id));

INSERT INTO parking_garage (name, capacity)
VALUES ('Garage A', 100);
INSERT INTO parking_slot (occupied, slot_number, parking_garage_id)
VALUES (FALSE, 1, 1);